springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui-custom.html
spring:
  data:
    mongodb:
      database: JobTracking
      uri: mongodb://127.0.0.1:27017
management:
 endpoints:
   web:
     exposure:
       include: '*'
 endpoint:
   health:
     show-details: always